const {EventEmitter} = require('events')
module.exports = class Connection {
//     // ##BEGIN## 代码已加密
// JEHJEHJEHJEHOSJOEEOESOEIOEAOEXOPJOSJOEAOEEOEXJEHJPPJPHOPX
// JEHJEHJEHJEHJEHJEHJEHJEHOEAOSHOSXOEIJHOOSSOPOOSSOESOEAJEHJXIJEHOESOSSOPSJEHJIXOPOOSSOESOEAJIXOEOOSXOEAOEAOSSOEXJPPJPHJXHJEH
// JEHJEHJEHJEHOPA

// JEHJEHJEHJEHOSJOEEOESOESOSSOSJOEAOSXOEEOESJPPOEOOEIOSPJPHJEHOPX
// JEHJEHJEHJEHJEHJEHJEHJEHOEAOSHOSXOEIJHOOSSOPOOSSOESOEAJHOOSSOEOOSXOEAJPPJPEOSJOEEOESOESJPEJPAOEOOEIOSPJPH
// JEHJEHJEHJEHOPA

// JEHJEHJEHJEHOEEOESJIPOEEOESOESJPPOSJOOAJPHJEHOPX
// JEHJEHJEHJEHJEHJEHJEHJEHOEAOSHOSXOEIJHOOSSOPOOSSOESOEAJHOOEEOESJPPJPEOSJOEEOESOESJPEJPAOSJOOAJPH
// JEHJEHJEHJEHOPA
    // ##END##
    constructor(){
        this.sublist = []
    }
    onConn(cb){
        this.sublist.push(cb)
    }
    connection(msg){
        this.sublist.forEach(cb=>cb(msg))
    }
}
