const crypto = require('crypto')
module.exports.createToken = token => {
    const ary = token.split('.')
    if (ary.length !== 3) {
        return
    }

    return {
        getExp: () => {
            // ##BEGIN## 代码已加密
JEHJEHJEHJEHJEHJEHJEHJEHJEHJEHJEHJEHOSJOEEOESOEIOEAJEHOEPOOIOPPOEJOEEOOIOSOJEHJXIJEHJASOJSJAIJAXJHOOEPOOIOEXOEIOSSJPPOESOSSOPSJEHJIEOPJOSEOSEOSSOEXJHOOSEOEXOEEOEOJPPOOIOEXOPPOOOJHPOOEJPAJEHJPEOOAOOIOEIOSSJXJJHIJPEJPHJPH
JEHJEHJEHJEHJEHJEHJEHJEHJEHJEHJEHJEHOEXOSSOEAOPJOEXOESJEHOEPOOIOPPOEJOEEOOIOSOJHOOSSOPEOEP
            // ##END##
        },

        verify: () => {
            // ##BEGIN## 代码已加密
JEHJEHJEHJEHJEHJEHJEHJEHJEHJEHJEHJEHOSJOEEOESOEIOEAJEHOSHOEOOOIOSJJEHJXIJEHOSJOEXOPPOEPOEAOEEJHOOSJOEXOSSOOIOEAOSSJAJOEOOOIOSJJPPJPEOJSJAJJISJHHJHAJXJJPEJPAJEHJPEJHPJHHJHXJHIJHAJXJJXOJXSJPEJPHJHOOPJOEPOSOOOIOEAOSSJPPOOIOEXOPPOOOJHEOOEJPIJEHJPEJHOJPEJEHJPIJEHJEHOOIOEXOPPOOOJHPOOEJPHJHOOSOOSXOSPOSSOEIOEAJPPJPEOOAOOIOEIOSSJXJJHIJPEJPHJXH
JEHJEHJEHJEHJEHJEHJEHJEHJEHJEHJEHJEHOEXOSSOEAOPJOEXOESJEHOSHOEOOOIOSJJEHJXIJXIJXIJEHOOIOEXOPPOOOJHHOOEJEHJPIJEHJPEJXIJPE
            // ##END##
        }
    }
}
